server:
  port: 6060
spring:
  mail:
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}

  application:
    name: Attendance
  datasource:
    url: jdbc:mysql://${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true    # SQL 보기 좋게 포맷팅
  cloud:
    gcp:
      enabled: true
      storage:
        bucket: fisa_final_project
        project-id: woven-coral-441407-d3
        credentials:
          location: ${GCP_KEY}
  batch:
    jdbc:
      initialize-schema: always
      table-prefix: BATCH_
    job:
      enabled: false